spheronFdn/docs

package.json, pages/_document.tsx
=> Add new GTM tag

pages/_app.tsx
=> Update meta og:image URL

pages/sdk/storage.mdx
Update the usage interaface only to include properties that are relevant for storage.
=> Update usage with limits interface for the Storage SDK

components/sdk.tsx, pages.config.ts, pages/sdk/_meta.json, pages/sdk/compute.mdx
completes https://linear.app/spheron/issue/SPH-1928/add-compute-sdk-docs
=> Compute SDK docs

pages/_app.tsx, pages/_meta.json, pages/billing/upgrade/arbitrum.mdx, pages/billing/upgrade/avalanche.mdx, pages/billing/upgrade/bsc.mdx, pages/billing/upgrade/gnosis.mdx, pages/billing/upgrade/optimism.mdx, pages/billing/upgrade/polygon.mdx, pages/billing/upgrade/solana.mdx, pages/compute/cluster.mdx, pages/framework-guide/deploy-next.mdx, pages/server-guide/nextjs.mdx, theme.config.tsx
=> Update docs og title

components/github-actions.tsx, components/quick-start.tsx, pages.config.ts, pages/_meta.json, pages/github-action.mdx, pages/github-actions.mdx, pages/github-actions/_meta.json, pages/github-actions/instance-update-action.mdx
=> Add github action docs

pages/billing/bonus.mdx, pages/billing/coupons.mdx, pages/billing/funds.mdx, pages/billing/upgrade/arbitrum.mdx, pages/billing/upgrade/avalanche.mdx, pages/billing/upgrade/bsc.mdx, pages/billing/upgrade/gnosis.mdx, pages/billing/upgrade/optimism.mdx, pages/billing/upgrade/polygon.mdx, pages/billing/upgrade/solana.mdx, pages/billing/wallet.mdx
Changes :
1. Made important sections in bold.
2. Double Quoted Click option.
=> Updating Doc

pages/billing/bonus.mdx, pages/billing/coupons.mdx, pages/billing/funds.mdx, pages/billing/upgrade/arbitrum.mdx, pages/billing/upgrade/avalanche.mdx, pages/billing/upgrade/bsc.mdx, pages/billing/upgrade/gnosis.mdx, pages/billing/upgrade/optimism.mdx, pages/billing/upgrade/polygon.mdx, pages/billing/upgrade/solana.mdx, pages/billing/wallet.mdx
* Update wallet.mdx
Changes :
2) Double Quoted Click option.
3) removed unnecessary and in the sentence.
* Update funds.mdx
Changes :
* Update Bonuses.mdx
Changes :
2) Double Quoted Click option.
* Update coupons.mdx
Changes :
2) "Double Quoted" click option.
3) Capitalized some characters.
* Update coupons.mdx
* Update polygon.mdx
Changes :
1)  Made important sections in bold.
3) Capitalize some characters.
4) Fixed troubleshoot part.
* Update optimism.mdx
Changes
3) Capitalize some characters.
4) Fixed troubleshooting …
=> Updating Doc (#52)

pages/organization/roles.mdx, pages/organization/settings.mdx
=> Improved Roles and Settings

pages/organization.mdx, pages/organization/roles.mdx, pages/organization/settings.mdx, pages/static/deployment/automation.mdx, pages/static/deployment/deployments.mdx, pages/static/deployment/logs.mdx
Changes:
3) Explained Stop Deployment & Redeploy Deployment more
=> Updated Git Provider & Logs, Git Automations, Manage Deployments Preview

pages/organization.mdx, pages/organization/roles.mdx, pages/organization/settings.mdx
Added necessary Note to the Organization section
=> Improving Organization Section

pages/static/projects/domain.mdx, pages/static/projects/ens.mdx, pages/static/projects/environments.mdx, pages/static/projects/handshake.mdx, pages/static/projects/https.mdx, pages/static/projects/private.mdx, pages/static/projects/variables.mdx
3) Added 2 Benefits in Handshake.
4) Added 2 Advantages in HTTPS.
3) Minor Correction in spelling.
=> Updating Static App > Projects Section

pages/framework-guide/deploy-angular.mdx, pages/framework-guide/deploy-brunch.mdx, pages/framework-guide/deploy-docusarus.mdx, pages/framework-guide/deploy-gatsby.mdx, pages/framework-guide/deploy-hugo.mdx, pages/framework-guide/deploy-iangular.mdx, pages/framework-guide/deploy-ireact.mdx, pages/framework-guide/deploy-next.mdx, pages/framework-guide/deploy-nuxt.mdx, pages/framework-guide/deploy-preact.mdx, pages/framework-guide/deploy-react.mdx, pages/framework-guide/deploy-sanity.mdx, pages/framework-guide/deploy-stencil.mdx, pages/framework-guide/deploy-svelte.mdx, pages/framework-guide/deploy-vanilla.mdx, pages/framework-guide/deploy-vite.mdx, pages/framework-guide/deploy-vue.mdx
3) Minor Correction in spelling.
4) Improved grammar.
=> Improving Framework Section

pages/sdk/storage-v2.mdx
This PR will add the new `inBackground` property to the `pinCid` function.
=> Add inBackground parameter to the pinCid function

next.config.js
Updated to nextra's new version with copy option in code snippet
=> Add copy functionality

pages/marketplace-guide/deso.mdx
=> Update deso node with a badge example

pages/cli.mdx
- Update CLI Page For Compute
- Removed Site and Storage form the CLI Page
=> Updated Spheron CLI Page

pages/core-concepts/payment-system.mdx, pages/core-concepts/providers.mdx, pages/fizz/reward-details.mdx, pages/providers/reward-details.mdx
Change ticket name from $SPHN to $SPON
=> Changed ticker name

pages/fizz/docker-resource-setup.mdx, pages/fizz/fizz-faq.mdx
1. Updated the older FAQ with new steps
2.  Added 88 FAQs
=> Updated FAQ

pages/providers/setup-provider.mdx
Updated Install helm charts section for provider setup
=> [PRO-1560] Updated Install helm charts section for provider setup
